name: grocery
description: ""
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  dio: ^5.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

